// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.pfmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.pfmApp',
  );
}

// ==================================================================================
// IMPORTANT: FIREBASE CONFIGURATION REQUIRED
// ==================================================================================
//
// This file contains placeholder Firebase configuration values.
// To use this app, you need to configure it with your actual Firebase project:
//
// OPTION 1: Automatic Configuration (Recommended)
// ------------------------------------------------
// 1. Install FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//
// 2. Login to Firebase:
//    firebase login
//
// 3. Run FlutterFire configure (from project root):
//    flutterfire configure
//
//    This will:
//    - Create/select a Firebase project
//    - Register your apps
//    - Generate this file with correct values
//
// OPTION 2: Manual Configuration
// --------------------------------
// 1. Go to Firebase Console: https://console.firebase.google.com
// 2. Create a new project or select an existing one
// 3. Add apps (Web, Android, iOS) and copy the configuration values
// 4. Replace the placeholder values in this file
// 5. Enable Email/Password authentication in Firebase Console
// 6. Create a Firestore database
//
// After configuration, enable Authentication:
// - Go to Firebase Console > Authentication > Sign-in method
// - Enable "Email/Password" provider
//
// Create Firestore Database:
// - Go to Firebase Console > Firestore Database
// - Click "Create database"
// - Start in test mode (you can set security rules later)
//
// ==================================================================================
